### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by chris-se**
As requested, this is a separate pull request for some minor fixes to open-isns.

### CODE REVIEW

**Comment by gonzoleeman** [comment]
My only (small) issue is that when you fall back to port 3205 I wonder if there should at least be an information or warning message in the log file, like "warning: falling back to default port 3205"?  Thanks for all the updates!

**Comment by chris-se** [comment]
I've pushed an additional patch to the pull request that adds the warning message + did some trivial tests to see that it works. On my system (isns not in /etc/services) it now prints the warning when the fallback is used at startup of isns binaries. (Unless the port is explicitly specified.)

**Comment by chris-se** [comment]
Thanks a lot for merging all of this, very much appreciated. :-)

Would it be possible for you to release a new version 0.96 with these changes (and the others you did before you merged mine)? Of course I could also make the initial package be based on a git snapshot, but using a release version looks much nicer.

**Comment by gonzoleeman** [comment]
Yes that seems possible. 

## 

Lee-Man Duncan

**Comment by chris-se** [comment]
Thank you very, very much for releasing a new version, and for your responsiveness to my pull requests. :+1:

**Pull request merged**
